name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: asia-southeast2
  SERVICE: ${{ secrets.SERVICE_ACCOUNT }}
  IMAGE: asia-southeast2-docker.pkg.dev/capstone-project-406502/jasane-api-cloudrun/jasane
  TAG: v1.1.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE }}
          export_default_credentials: true

      - name: Build and Push the Docker image
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
          docker build -t ${{ env.IMAGE }}:latest .
          docker push ${{ env.IMAGE }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --port 8080
